### ISSUE TITLE
undefined: AssetNames and MustAsset

### ISSUE THREAD

**Issue by astenmies** [OscarYuen/go-graphql-starter#5]
Hi, I'm very interested in taking a look at this project and maybe contribute. But I'm getting the following error... Could you please enlighten me on what's going on?
Thanks in advance

```bash
$ go build server.go
# github.com/OscarYuen/go-graphql-starter/schema
../github.com/OscarYuen/go-graphql-starter/schema/schema.go:9:23: undefined: AssetNames
../github.com/OscarYuen/go-graphql-starter/schema/schema.go:10:8: undefined: MustAsset
```

**Comment by OscarYuen** [comment]
@astenmies 
Hello, the most convenient way is to install databind by the following command
`go get -u github.com/jteeuwen/go-bindata/...`

p.s. the ... must be included in order to install the executable command
then you need to ensure your GOPATH is added to your PATH environment variable of your OS
Then you could run the databind command on your terminal/CMD

The databind command is to generate go code from the static resources. In this repository, it generates go code from graphql static file.
You could either run the following databind command on the root path of this project

`go-bindata -ignore=\.go -pkg=schema -o=schema/bindata.go schema/...`

OR 

`go generate ./schema`

Then you would see `bindata.go` is generated under schema folder. And the undefined variable can be resolved. Thanks~

**Comment by astenmies** [comment]
@OscarYuen Thanks, I just noticed it's because of the remote path to schema.

In server.go, `github.com/OscarYuen/go-graphql-starter/schema`, should this not be `./schema`?  Because `databind.go` is ignored (by .gitignore), it can't find AssetNames and MustAsset...

Thanks

**Comment by OscarYuen** [comment]
@astenmies 
For go development, it is advised officially to put your project under your GOPATH and avoid relative path. If we put our project under GOPATH, and run databind, the server.go would find the undefined variable as the files in scheme path in server.go have already changed

**Comment by OscarYuen** [comment]
I would close the issue since no further enquires received
